 ALTER TABLE PRODUIT
ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (cat_code) REFERENCES CATEGORIE(cat_code);

ALTER TABLE COMMANDE
ADD CONSTRAINT FK_COM_CLI FOREIGN KEY (clt_code) REFERENCES CLIENT(clt_code);

ALTER TABLE CONTENIR
ADD CONSTRAINT FK_CONT_COM FOREIGN KEY(numCom) REFERENCES COMMANDE(numCom);

ALTER TABLE CONTENIR
ADD CONSTRAINT FK_CONT_PROD FOREIGN KEY(pdt_ref ) REFERENCES PRODUIT(pdt_ref );